Clear OwnerReferences on knative-local-gateway Service (fixes #507)
knative/operator pull request #567
Opened 2021-04-29 18:21 UTC by polivbr

Kubernetes v1.20+ does not allow cross-namespace owner references
and will cause the resource to be considered invalid and will
garbage collect it.

Because the knative-local-gateway service has its namespace
changed to istio-system, it's owner reference to the operator
is invalid, and it must be removed.

Fixes #

## Proposed Changes

*
*
*

**Release Note**

```release-note

```

2021-04-30 10:44 UTC, nak3 commented
/ok-to-test

2021-05-04 14:01 UTC, houshengbo commented
@polivbr You made a good point. The `knative-local-gateway` Service also leads to some other issues, like https://github.com/knative/operator/issues/565.

2021-05-07 15:57 UTC, maximilien requested changes
See comment.

2021-05-07 15:57 UTC, maximilien commented on pkg/reconciler/knativeserving/common/ingress_service.go
> +			u.SetOwnerReferences(nil)
BTW, I can comment this line 31 and all tests passing... so clearly need to add test to cover this chance. Thx.

2021-05-12 20:44 UTC, houshengbo commented
@polivbr @maximilien 
I am thinking of accepting this PR by now, coz we are close to the release of 0.23. Would like to get this issue resolved.
In terms of test cases, it is saved in my `cache memory`.

2021-05-12 20:48 UTC, houshengbo commented
https://github.com/knative/operator/issues/586 TO be resolved.
/lgtm
/approve

2021-05-12 20:49 UTC, polivbr commented
I'm stuck with getting my company's legal department to sign off on the CLA.

It's such a trivial fix... can someone else just replicate it if the lack of a corporate CLA is an issue?

2021-05-12 20:53 UTC, maximilien commented
> In terms of test cases, it is saved in my `cache memory`.

Or better, create an issue for it :)

2021-05-12 21:06 UTC, merged